# Replace paths before use
model:
  source_path: /ABSOLUTE/PATH/TO/COLMAP_SCENE
  model_path: output/colmap/run_r2
  resolution: 2

optimization:
  iterations: 30100
  opacity_lr: 0.05
  prune_big_point_after_iter: 30000

train:
  disable_viewer: true

