# Replace paths before use
model:
  source_path: /ABSOLUTE/PATH/TO/EgoNeRF/OmniBlender/<sequence>
  model_path: output/egonerf/omniblender/<sequence>

optimization:
  iterations: 32010
  opacity_lr: 0.05
  prune_by_extent: false

train:
  disable_viewer: true

