model:
  source_path: /ABSOLUTE/PATH/TO/DATASET
  model_path: output/sample_run
  images: images
  depths: ""
  resolution: -1
  white_background: false
  train_test_exp: false
  data_device: cuda
  eval: false
  camera_type: auto  # auto|pinhole|lonlat

optimization:
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 0.0000016
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.025
  scaling_lr: 0.005
  rotation_lr: 0.001
  exposure_lr_init: 0.01
  exposure_lr_final: 0.001
  exposure_lr_delay_steps: 0
  exposure_lr_delay_mult: 0.0
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 3000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
  densify_min_opacity: 0.005
  prune_by_extent: true
  prune_big_point_after_iter: 0
  skip_bottom_ratio: 0.0
  erp_weighted_loss: false
  erp_weighted_metrics: false
  depth_l1_weight_init: 1.0
  depth_l1_weight_final: 0.01
  random_background: false
  optimizer_type: default  # default|sparse_adam

pipeline:
  convert_SHs_python: false
  compute_cov3D_python: false
  debug: false
  antialiasing: false
  rasterizer: omnigs  # omnigs|diff

train:
  seed: 0
  test_iterations: [7000, 30000]
  save_iterations: [7000, 30000]
  checkpoint_iterations: []
  start_checkpoint: null
  disable_viewer: true
  quiet: false
  ip: 127.0.0.1
  port: 6009
  debug_from: -1
  detect_anomaly: false

